apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cdkelley93-cdkelley93-poi-map-app-dev
  annotations:
    argocd/app-name: cdkelley93-cdkelley93-poi-map-app-dev
    backstage.io/kubernetes-id: cdkelley93-cdkelley93-poi-map-app-dev
    backstage.io/kubernetes-namespace: cdkelley93
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=cdkelley93-cdkelley93-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/cdkelley93-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/cdkelley93/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/cdkelley93/deployments/cdkelley93-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/cdkelley93-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://cdkelley93-poi-map-app-cdkelley93.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/cdkelley"
  system: workshop-system-cdkelley93
  consumesApis:
    - gateway-api-cdkelley93
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-cdkelley93
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/cdkelley"
